export default {
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT',
  USER_REGISTER_EXISTS: 'USER_REGISTER_EXISTS',
  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  CODE_NOT_EQUAL: 'CODE_NOT_EQUAL',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  ACCOUNT_DISABLE: 'ACCOUNT_DISABLE'
}
