const API_GATEWAY_TEST = 'http://localhost:5000'
const API_GATEWAY_RELEASE = 'http://swn.vietan-software.com:5000'

const AUTH_API = API_GATEWAY_RELEASE
const CATEGORY_API = API_GATEWAY_RELEASE
const STATION_AUTO_API = API_GATEWAY_RELEASE
const PORT_DEPLOY = 5555

module.exports.API_GATEWAY_TEST = API_GATEWAY_TEST
module.exports.API_GATEWAY_RELEASE = API_GATEWAY_RELEASE
module.exports.AUTH_API = AUTH_API
module.exports.CATEGORY_API = CATEGORY_API
module.exports.STATION_AUTO_API = STATION_AUTO_API
module.exports.PORT_DEPLOY = PORT_DEPLOY

module.exports.default = {
	API_GATEWAY_TEST,
	API_GATEWAY_RELEASE,
	AUTH_API,
	CATEGORY_API,
	STATION_AUTO_API,
	PORT_DEPLOY
}
